@startuml
title Диаграмма компонентов сервиса управления устройствами освещения

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(WarmhouseSystem, "Система 'Тёплый дом'") {
  Container(LightningService, "Микросервис управления устройствами освещения", "Java, Spring Boot", "Обеспечивает управление устройствами освещения и получение показателей освещенности от их датчиков")
  Container(APIGateway, "Шлюз API", "Kong", "Маршрутизация API на сервисы")
  ContainerDb(LightningDB, "База данных сервиса устройств освещения", "PostgreSQL", "Хранит данные о запросах на управление, текущем состоянии и последних показаниях датчиков освещенности")
  ContainerQueue(LightningQueue, "Очередь с топиками для устройств освещения", "Kafka", "Сюда помещаются данные о состоянии устройств освещения, показатели датчиков освещенности и телеметрия")
  Container_Ext(SmartHomeGate, "Шлюз умного дома", "Управляет и обеспечивает обмен данными со всеми умными устройствами этого дома")
}

Container(LightningService, "Микросервис управления устройствами освещения", "Java, Spring Boot", "Обеспечивает управление устройствами освещения и получение показателей освещенности от их датчиков") {
  Component(ServiceLayer, "Бизнес-логика сервиса", "Бизнес-логика работы с устройствами освещения")
  Component(RepositoryLayer, "Репозиторий хранения данных", "Логика работы с БД")
  Component(DeviceInteropLayer, "Работа с устройствами", "Поддержка протоколов, специфическая для устройств логика запроса состояния, показания датчиков, телеметрии, подача команд на управление")
}

Rel(APIGateway, ServiceLayer, "Запрос состояния и показателей датчиков, команды на управление")
Rel(ServiceLayer, APIGateway, "Состояние устройств, показатели датчиков, квитанции о выполнении команд, уведомления")

Rel(ServiceLayer, RepositoryLayer, "Текущее состояние устройств, текущие показатели датчиков")
Rel(RepositoryLayer, ServiceLayer, "Последние сохранённые состояния устройств, показатели датчиков")
Rel(RepositoryLayer, LightningDB, "Обмен данными с СУБД")

Rel(ServiceLayer, LightningQueue, "Состояние устройств, показатели датчиков, полученные команды на управление")
Rel(LightningQueue, ServiceLayer, "Последние (еще не выполненные) команды на управление")

Rel(ServiceLayer, DeviceInteropLayer, "Запросы текущего состояния и показаталей, команды на управление")
Rel(DeviceInteropLayer, ServiceLayer, "Состояние устройств, показатели датчиков, телеметрия")

Rel(DeviceInteropLayer, SmartHomeGate, "Запросы состояния устройств, показаний датчиков, телеметрии, команды на управление")
Rel(SmartHomeGate, DeviceInteropLayer, "Текущее состояние устройств, показания датчиков, телеметрия")

@enduml
