@startuml
title Диаграмма компонентов сервиса управления дверьми, замками, воротами

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(WarmhouseSystem, "Система 'Тёплый дом'") {
  Container(DoorControlService, "Микросервис управления дверьми, замками, воротами", "Java, Spring Boot", "Обеспечивает управление дверьми, замками, воротами и получение состояния (заперто, отперто)")
  Container(APIGateway, "Шлюз API", "Kong", "Маршрутизация API на сервисы")
  ContainerDb(DoorControlDB, "База данных сервиса управления дверьми", "PostgreSQL", "Хранит данные о запросах на управление, текущем состоянии и последних показаниях датчиков закрытия/открытия")
  ContainerQueue(DoorControlQueue, "Очередь с топиками для дверей, замков, ворот", "Kafka", "Сюда помещаются данные о состоянии дверей, замков, ворот, показатели датчиков открытия/закрытия и телеметрия")
  Container_Ext(SmartHomeGate, "Шлюз умного дома", "Управляет и обеспечивает обмен данными со всеми умными устройствами этого дома")
}

Container(DoorControlService, "Микросервис управления устройствами дверей, замков, ворот", "Java, Spring Boot", "Обеспечивает управление устройств дверей, замков, ворот и получение состояния открытости от их датчиков") {
  Component(ServiceLayer, "Бизнес-логика сервиса", "Бизнес-логика работы с устройствами дверей, замков, ворот")
  Component(RepositoryLayer, "Репозиторий хранения данных", "Логика работы с БД")
  Component(DeviceInteropLayer, "Работа с устройствами", "Поддержка протоколов, специфическая для устройств логика запроса состояния, показания датчиков, телеметрии, подача команд на управление")
}

Rel(APIGateway, ServiceLayer, "Запрос состояния и показателей датчиков, команды на управление")
Rel(ServiceLayer, APIGateway, "Состояние устройств, показатели датчиков, квитанции о выполнении команд, уведомления")

Rel(ServiceLayer, RepositoryLayer, "Текущее состояние устройств, текущие показатели датчиков")
Rel(RepositoryLayer, ServiceLayer, "Последние сохранённые состояния устройств, показатели датчиков")
Rel(RepositoryLayer, DoorControlDB, "Обмен данными с СУБД")

Rel(ServiceLayer, DoorControlQueue, "Состояние устройств, показатели датчиков, полученные команды на управление")
Rel(DoorControlQueue, ServiceLayer, "Последние (еще не выполненные) команды на управление")

Rel(ServiceLayer, DeviceInteropLayer, "Запросы текущего состояния и показаталей, команды на управление")
Rel(DeviceInteropLayer, ServiceLayer, "Состояние устройств, показатели датчиков, телеметрия")

Rel(DeviceInteropLayer, SmartHomeGate, "Запросы состояния устройств, показаний датчиков, телеметрии, команды на управление")
Rel(SmartHomeGate, DeviceInteropLayer, "Текущее состояние устройств, показания датчиков, телеметрия")

@enduml
