@startuml

entity "Клиент" as user {
    *id : number <<generated>>
    --
    *full_name : text
    *phone_number : text
    email : text
    *support_staff : bool
}

entity "Группа клиентов" as user_group {
    *id : number <<generated>>
    *creator_user_id : number <<FK>>
    --
    *name : text
}

entity "Участник группы" as group_participant {
    *id : number <<generated>>
    *user_group_id : number <<FK>>
    *user_id : number <<FK>>
    *has_admin_rights : bool
}

entity "Дом" as home {
    *id : number <<generated>>
    --
    *creator_user_id : number <<FK>>
    *user_group_id : number <<FK>>
    *address : text
}

entity "Умный шлюз" as smarthomegate {
    *id : uuid <<generated>>
    *home_id : id <<FK>>
    *user_group_id : number <<FK>>
    --
    *name : text
    *state : enum('registered', 'online', 'offline', 'failed', 'blocked')
    manufacturer : text
    serial_number : text
}

entity "Тип устройства" as device_type {
    *id : uuid <<PK>>
    *name : text
    --
    description : text
}

entity "Устройство" as device {
    *id : uuid <<generated>>
    *type_id : number <<FK>>
    *home_id : number <<FK>>
    *gate_uuid : uuid <<FK>>
    --
    *name : text
    *state : enum('registered', 'online', 'offline', 'failed', 'blocked')
    manufacturer : text
    serial_number : text
}

entity "Тип команды" as command_type {
    *id : number <<PK>>
    *name : text
    *description : text
    *value_type : enum('none,'boolean','text','number','float','json')
    --
    physical_type : text
    js_schema : text
}

entity "Тип показания" as sample_type {
    *id : number <<PK>>
    *name : text
    *description : text
    *value_type : enum('boolean','text','number','float','json')
    *physical_type : text
    --
    js_schema : text
}

entity "История команд" as command_history {
    *id : number <<PK>>
    *device_id : number <<FK>>
    *command_type_id : number <<FK>>
    *time : timestamp
    --
    boolean_value : boolean
    text_value : text
    number_value : number
    float_value : float
    json_value : text
}

entity "История показаний" as samples_history {
    *id : number <<PK>>
    *device_id : number <<FK>>
    *sample_type_id : number <<FK>>
    *time : timestamp
    --
    boolean_value : boolean
    text_value : text
    number_value : number
    float_value : float
    json_value : text
}

entity "Триггер" as trigger {
    *id : number <<PK>>
    name : text
    *owner : number <<FK>>
}

entity "Условие для триггера" as trigger_condition {
    *id : number <<PK>>
    *trigger_id : number <<FK>>
    *device_id : number <<FK>>
    *sample_type_id : number <<FK>>
    *operator_type_1 : enum('equal','not_equal','lesser','lesser_equal','greater','greater_equal','matches','in_range', 'out_range')
    *value_1 : text
    operator_type_2 : enum('equal','not_equal','lesser','lesser_equal','greater','greater_equal','matches','in_range', 'out_range')
    value_2 : text
}

entity "Действие" as action {
    *id : number <<PK>>
    name : text
    *owner : number <<FK>>
}

entity "Команда от действия" as action_command {
    *id : number <<PK>>
    name : text
    *action_id : number <<FK>>
    *device_id : number <<FK>>
    *command_type_id : number <<FK>>
    --
    boolean_value : boolean
    text_value : text
    number_value : number
    float_value : float
    json_value : text
}

home ||--o{ user : "принадлежит"
home }--|| user_group : "имеет группу жильцов"

user_group }--|| user : "создана клиентом"

smarthomegate }--|| home : "находится в доме"
smarthomegate }--|| user_group : "используется группой жильцов"

group_participant }--|| user : "является клиентом"
group_participant }--|| user_group : "участвует в группе жильцов"

device }--|| home : "расположено в"
device }--|| device_type : "имеет тип"
device }--|| smarthomegate : "под управлением"

command_history }--|| command_type : "имеет тип команды"
command_history }--|| device : "от устройства"

samples_history }--|| sample_type : "имеет тип показания"
samples_history }--|| device : "от устройства"

trigger }--|| user : "его создатель и владелец"
trigger_condition }--|| trigger : "относится к триггеру"
trigger_condition }--|| device : "для устройства"
trigger_condition }--|| sample_type : "имеет тип показания"

action }--|| user : "его создатель и владелец"
action_command }--|| action : "относится к действию"
action_command }--|| device : "относится к устройству"
action_command }--|| command_type: "имеет тип команды"

@enduml
